### ISSUE TITLE
Google colab not working.

### ISSUE THREAD

**Issue by machakw21** [oxai/deepsaber#7]
I have tried running this by pulling the song from youtube and a copy I have, I get the same error.

Generating level for Diesel_Not_Petrol.mp3
Traceback (most recent call last):
  File "generate_stage1.py", line 94, in <module>
    first_samples = torch.full((1,opt.output_channels,receptive_field//2),constants.START_STATE)
RuntimeError: Providing a bool or integral fill value without setting the optional `dtype` or `out` arguments is currently unsupported. In PyTorch 1.7, when `dtype` and `out` are not set a bool fill value will return a tensor of torch.bool dtype, and an integral fill value will return a tensor of torch.long dtype.
usage: generate_stage2.py [-h] [--song_path SONG_PATH] [--json_file JSON_FILE]
                          [--experiment_name EXPERIMENT_NAME]
                          [--checkpoint CHECKPOINT]
                          [--temperature TEMPERATURE] [--bpm BPM]
                          [--generate_full_song] [--use_beam_search]
                          [--open_in_browser] [--cuda]
generate_stage2.py: error: unrecognized arguments: the model from ../../scripts/training/block_placement_ddc2/iter_130000_net_.pth
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-e647f4c5105c> in <module>()
      8 get_ipython().system("cd scripts/generation; chmod +x ./script_generate.sh; ./script_generate.sh '../../songs/'{filename}")
      9 generated_filename = get_ipython().getoutput('ls -t scripts/generation/generated')
---> 10 generated_filename=generated_filename[0]
     11 get_ipython().system('cp scripts/generation/generated/{generated_filename} ../../../')
     12 # files.download("scripts/generation/generated/"+generated_filename)

IndexError: list index out of range

**Comment by FreezFree** [comment]
Works by downgrading PyTorch in the Colab:
`!pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html`

Solution found on the DeepRhythm Discord server (By grn_trtle#0923).

**Comment by Kowleone** [comment]
I have a similar problem! 

I just run without changing any {Filename}

Generating level for Some_Things_Never_Change_From_Frozen_2_Lyric_Video.mp3
mkdir: cannot create directory ‘generated’: File exists
Traceback (most recent call last):
  File "generate_stage1.py", line 72, in <module>
    model.setup()
  File "/content/drive/My Drive/deepsaber_tmp/models/base_model.py", line 90, in setup
    self.load_networks(load_suffix)
  File "/content/drive/My Drive/deepsaber_tmp/models/base_model.py", line 228, in load_networks
    state_dict = torch.load(load_path, map_location=str(self.device))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../../scripts/training/block_placement_ddc2/iter_130000_net_.pth'
usage: generate_stage2.py [-h] [--song_path SONG_PATH] [--json_file JSON_FILE]
                          [--experiment_name EXPERIMENT_NAME]
                          [--checkpoint CHECKPOINT]
                          [--temperature TEMPERATURE] [--bpm BPM]
                          [--generate_full_song] [--use_beam_search]
                          [--open_in_browser] [--cuda]
generate_stage2.py: error: unrecognized arguments: the model from ../../scripts/training/block_placement_ddc2/iter_130000_net_.pth

Please advise on any chnages to code to get this working

**Comment by guillefix** [comment]
Hi, sorry for late reply

@machakw21 , thanks for the report. I think it was a problem with an pudate in pytorch. I think I've fixed it now. Can you try again?

@Kowleone Did you run the cell titled "Prepare deepsaber and dependencies" ? If it still doesn't work try opening the page again, change the `deepsaber_folder_name` and run the cells, so that it would download deepsaber from scratch again.

**Comment by JackHiltini** [comment]
Having a similar issue of sorts, granted, really new to this and I am unsure what I may be doing wrong but so far it will not let me get past the first step of downloading songs from YouTube to use for this. 

#@title Get song
#@markdown Choose to download song from youtube, otherwise it asks you to upload file
download_from_youtube = True #@param {type:"boolean"}
youtube_url = 'https://www.youtube.com/watch?v=BNXKppay2j0' #@param {type:"string"}
if download_from_youtube:
  !export youtube_url
  !youtube-dl -x --audio-format mp3 --restrict-filenames $youtube_url
  filename=!youtube-dl -x --audio-format mp3 --get-filename --restrict-filenames $youtube_url
  filename = os.path.splitext(filename[0])[0]+".mp3"
  filename_new = filename[:50]+".mp3"
  !mv $filename songs/$filename_new
  filename = filename_new
else:
  res=files.upload()
  filename=list(res.keys())[0]
  os.rename(filename,"songs/"+filename)
